spring:
  application:
    name: Payment
  datasource:
    url: jdbc:postgresql://localhost:5432/Payment
    username: devuser
    password: devpassword 
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

microservices:
  order: http://localhost:8001
  user: http://localhost:8002
  notification: http://localhost:8004

server:
  port: 8006
